### ISSUE TITLE
Android: always ignore first record created

### ISSUE THREAD

**Issue by fredhuha** [enisn/Xamarin.Forms.Contacts#2]
Hi,

On android devices always first contact created is ignored. If you have 1 contact show no contact, 2 show 1, 3 show 2 and so on.

Maybe this can be the reason on Plugin/ContactService/Platforms/Android/**ContactServiceImplementation.cs**

![image](https://user-images.githubusercontent.com/39374167/40177389-dd1f39a4-59b4-11e8-9174-0efcfc350bdb.png)

"_if (cursor.MoveToFirst())_" you move to first record, but you do nothing, then you "_while (cursor.MoveToNext())_" and move to second record and start to put records into a list.

**Comment by enisn** [comment]
You can create a pull request to change it,

I'll work on it as soon as possible,

**Comment by enisn** [comment]
It just solved at #4  by @sadgit 
And it'll be available on [Nuget version 1.0.5](https://www.nuget.org/packages/Xamarin.Forms.Contacts/1.0.5) and above
